---
title: "Домашка - 1"
date: "2017-03-17"
output: pdf_document
lang: ru-RU
---

1. Скачайте файл с данными `Advertising.csv` и загрузите его в R под именем  `advertising`.

2. Сколько переменных в наборе данных? Как они называются?

Продажи — в тысячах штук, все расходы — в тысячах долларов.

2. Удалите из набора переменную отвечающую за номер наблюдения. Получившийся набор данных назовите `adv2`.

3. Посчитайте описательные статистики для набора данных `adv2`:
    1. Чему равны средние расходы на рекламу на телевидении? 
    1. Чему равны максимальные расходы на рекламу в газетах?
3. Отсортируйте наблюдения по убыванию продаж. Получившийся набор данных назовите `adv_sorted`.
4. Отберите 100 наблюдений с самыми высокими продажами. Получившийся набор данных назовите `adv_top100`.
3. Посчитайте описательные статистики для набора данных `adv_top100`:
    1. Чему равны средние расходы на рекламу на телевидении? 
    1. Чему равны максимальные расходы на рекламу в газетах?
5. Выполните действия 3, 5, 6, 7 без промежуточного создания новых наборов данных:
    * с использованием традиционного синтаксиса Эйлера-Клеро;
    * с использованием `трубочек`.
