---
title: "Количественный анализ социальных данных с помощью пакета R"
output: html_document
lang: ru-RU
---

## Семинары:


* 17 марта 2017, ауд. 324. Установка R, Rstudio. Где найти справку. Загрузка .csv файлов. Отбор переменных, сортировка, описательные статистики. Создание векторов. NA/NaN. Файлы: [script_01.R](https://github.com/bdemeshev/r_socio_hse/raw/master/script_01.R) и [домашка-1](https://github.com/bdemeshev/r_socio_hse/raw/master/ht_01.pdf).


* 24 марта 2017, ауд. 320а. Отбор наблюдений, простые графики: диаграмма рассеяния и гистограмма. Создание новых наблюдений. Сохранение .csv файлов. Файлы: [script_02.R](https://github.com/bdemeshev/r_socio_hse/raw/master/script_02.R) и домашка-2 (скоро будет)





* 05 апреля 2017, ауд. 320а. группировка данных, слияние таблиц, работа с факторными переменными. Стратегия "Разделяй и властвуй" (split-apply-combine strategy).  [script_03.R](https://github.com/bdemeshev/r_socio_hse/raw/master/script_03.R)



* 19 апреля 2017, ауд. 326. Сохранение данных. Метод наименьших квадратов. Извлекаем прогнозные значения, остатки, строим графики. Грамотное программирование — начало, [script_04.R](https://github.com/bdemeshev/r_socio_hse/raw/master/script_04.R), [report.Rmd](https://github.com/bdemeshev/r_socio_hse/raw/master/report.Rmd). 


* 21 апреля 2017, ауд. 319а. Грамотное программирование — продолжение: [report_2.Rmd](https://github.com/bdemeshev/r_socio_hse/raw/master/report_2.Rmd).

* 28 апреля 2017, ауд. 320а.  Грамотное программирование — окончание. R с менюшками: radiant, мелкие помощники addins: [report_3.Rmd](https://github.com/bdemeshev/r_socio_hse/raw/master/report_3.Rmd). Шаблон [shablon_2.docx](https://github.com/bdemeshev/r_socio_hse/raw/master/shablon_2.docx) для компиляции отчёта.



* 12 мая 2017, ауд. 320а. LASSO, авто-ARIMA, взвешенная регрессия. Пожалуйста, поставьте заранее пакеты `forecast`, `sophisthse`, `forecastHybrid`, `glmnet`, `survey`, `listviewer`, `gapminder`, `stargazer`. [report_4.Rmd](https://github.com/bdemeshev/r_socio_hse/raw/master/report_4.Rmd).



* 17 мая 2017, ауд. 324. Тестирование гипотез о коэффициентах в линейной модели. Lasso. Logit и предельные эффекты. [report_5.Rmd](https://github.com/bdemeshev/r_socio_hse/raw/master/report_5.Rmd).

План:

* 19 мая 2017, ауд. 320а.  Иерархические модели — окончание. Вопросы-ответы.  Пожалуйста, перед началом занятия поставьте: STAN: [инструкция по-русски](https://bdemeshev.github.io/installation/r_stan/r_stan_installation.html), официальный [сайт STAN](http://mc-stan.org), `rstanarm`, `shinystan`, `bayesplot`, `loo`.

Место: Мясницкая 9/11. Приносите свои ноутбуки!!

По возможности будут [видео записи лекций](https://www.youtube.com/playlist?list=PL1poMUvVlAqcma4pOO_ldFxang7D2CsVi).

## Финальное эссе уже можно начинать :)

1. Взять любой свой набор данных.

2. Построить не менее 3 (трёх) графиков.

3. Оценить не менее 1 (одной)  регрессии с помощью МНК.

4. Отобрать желаемое количество регрессоров с помощью LASSO.

5. Включить в итоговый отчет симпатичную табличку.

6. top-secret

...

Финальное эссе нужно выполнить с использование R+markdown. 

## Установка софта:

* [R + Rstudio](http://bdemeshev.github.io/installation/r/R_installation.html)
* [stan / rstan](http://bdemeshev.github.io/installation/r_stan/r_stan_installation.html)
* [Atom](https://atom.io/)
* [Texlive](https://www.tug.org/texlive/)
* [Anaconda](https://www.continuum.io/downloads)

## Данные

* [Покемоны](https://github.com/bdemeshev/r_socio_hse/raw/master/datasets/pokemon.csv)
* [Advertising](http://www-bcf.usc.edu/~gareth/ISL/Advertising.csv)


## Материалы

* Кабаков Р.И. R в действии. [Анализ и визуализация данных на языке R](http://kek.ksu.ru/eos/WM/Kabacoff2014ru.pdf)
* Шипунов А.Б., Балдин Е.М. и др. [Наглядная статистика. Используем R!](http://ashipunov.info/shipunov/school/books/rbook.pdf) 
* Мастицкий С.Э., Шитиков В.К., [Статистический анализ и визуализация с помощью R](http://www.ievbras.ru/ecostat/Kiril/R/Mastitsky%20and%20Shitikov%202014.pdf)
* [Шпаргалки по R](https://www.rstudio.com/resources/cheatsheets/) от Rstudio
* Tibshirani, [An introduction to statistical learning](http://www-bcf.usc.edu/~gareth/ISL/)

### На русском также могут быть полезны:

* Стилевое руководство гугла:
[english](https://google-styleguide.googlecode.com/svn/trunk/Rguide.xml),
[русский](https://9ccb6b88-a-cba0391b-s-sites.googlegroups.com/a/kiber-guu.ru/r-practice/links/R_style_from_Google.pdf?attachauth=ANoY7crkge5FhA5LZtMwj6Ilur-WbnkKLijkDkoB01VZZAlsFoRjEo7YwgqvW-Gid6ffwBmz3TMT51kMnw8JljZeQlDPRXMKZctirezqTziipn5TOaB9D1IaQ7qzTSusjkIyYV2jMchrhAsXOHTo_G0VRztBxYeecm4HYS19M1VTxn-UluL_9tYpsOEpDvhV1ghlRvk57pCxDO3C4wSV63SQIy0p7cjo6r-HB6Dj0CG7iNKM_RTjaAw%3D&attredirects=0)
* [Блог r-analytics](http://r-analytics.blogspot.ru). На нём есть несколько
других подборок русскоязычных ресурсов по R:
[раз](http://r-analytics.blogspot.ru/p/blog-page_20.html) и
[два](http://r-analytics.blogspot.ru/p/blog-page_80.html). 
* Группы вконтакте: [rstatistics](https://vk.com/rstatistics), [spbrug](https://vk.com/spbrug), [introstats](https://vk.com/introstats) 
* Венэбльз, Смит [Введение в R](http://www.ievbras.ru/ecostat/Kiril/R/Biblio/R_rus/Venables%20%c2%e2%e5%e4%e5%ed%e8%e5%20%e2%20R.pdf)
* Зарядов И.С. Введение в R: [часть 1](http://www.ievbras.ru/ecostat/Kiril/R/Biblio/R_rus/%c7%e0%f0%ff%e4%ee%e2%20%f7%e0%f1%f2%fc_1.pdf), [часть 2](http://www.ievbras.ru/ecostat/Kiril/R/Biblio/R_rus/%c7%e0%f0%ff%e4%ee%e2%20%f7%e0%f1%f2%fc_2.pdf)
* Борис Демешев [Цикл маленьких заметок по R](http://bdemeshev.github.io/r_cycle/)

### Вопросы и ответы:

* [stackoverflow](http://stackoverflow.com/) Если возникли проблемы с
программированием в R (и не только в R), а документация уже прочитана...
* [stats.stackexchange](http://stats.stackexchange.com/) Можно спросить по
статистическим методам и их реализации в R.
* [tex.stackexchange](http://tex.stackexchange.com/) Вопросы и ответы про LaTeX




-------
Созданные [мной](https://bdemeshev.github.io/about/) для данного курса материалы распространяются по лицензии [Creative Commons Attribution-NonCommercial-ShareAlike](http://creativecommons.org/licenses/by-nc-sa/3.0/deed.ru)
